version: '3'
services:
  web:
    image: nginx:1.13.5-alpine
    ports:
      - "8085:80"
    depends_on:
      - app
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/var/www/html

  app:
    image: php:7.1.9-fpm-alpine
    volumes:
      - ./public_html:/var/www/html